using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Microsoft.SqlServer.Dac.Model;
using MSBuild.Sdk.SqlProj.DacpacTool.Diagram.Model;

#nullable enable

namespace MSBuild.Sdk.SqlProj.DacpacTool.Diagram
{
    public static class DacpacModelFactory
    {
        private static readonly HashSet<string> DateTimePrecisionTypes =
            new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            { "datetimeoffset", "datetime2", "time" };

        private static readonly HashSet<string> MaxLengthRequiredTypes =
            new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            { "binary", "varbinary", "char", "varchar", "nchar", "nvarchar" };


        public static IList<SimpleTable> GetTablesFromModel(TSqlModel model)
        {
            ArgumentNullException.ThrowIfNull(model);

            var typeAliases = GetTypeAliases(model);
            var tableComments = GetTableComments(model);
            var columnComments = GetColumnComments(model);

            var tableObjects = model
                .GetObjects(DacQueryScopes.UserDefined, Table.TypeClass)
                .Where(t => !t.GetProperty<bool>(Table.IsAutoGeneratedHistoryTable))
                .ToList();

            var tables = new List<SimpleTable>();
            var tablesByKey = new Dictionary<string, SimpleTable>(StringComparer.OrdinalIgnoreCase);

            foreach (var tableObj in tableObjects)
            {
                var schema = tableObj.Name.Parts[0];
                var name = tableObj.Name.Parts[1];

                tableComments.TryGetValue($"{schema}.{name}", out var tableComment);

                var simpleTable = new SimpleTable
                {
                    Name = name,
                    Schema = schema,
                    Comment = tableComment,
                };

                foreach (var colObj in tableObj.GetReferenced(Table.Columns, DacQueryScopes.UserDefined))
                {
                    var colType = colObj.GetMetadata<ColumnType>(Column.ColumnType);
                    if (colType == ColumnType.ComputedColumn)
                    {
                        continue;
                    }

                    var colName = colObj.Name.Parts[2];
                    var isNullable = colObj.GetProperty<bool>(Column.Nullable);
                    var storeType = GetColumnStoreType(colObj, typeAliases);

                    columnComments.TryGetValue($"{schema}.{name}.{colName}", out var colComment);

                    simpleTable.Columns.Add(new SimpleColumn
                    {
                        Name = colName,
                        StoreType = storeType,
                        IsNullable = isNullable,
                        Comment = colComment,
                    });
                }

                tables.Add(simpleTable);
                tablesByKey[$"{schema}.{name}"] = simpleTable;
            }

            foreach (var pkObj in model.GetObjects(DacQueryScopes.UserDefined, PrimaryKeyConstraint.TypeClass))
            {
                var hostRefs = pkObj.GetReferenced(PrimaryKeyConstraint.Host, DacQueryScopes.UserDefined).ToList();
                if (hostRefs.Count == 0)
                {
                    continue;
                }

                var host = hostRefs[0];
                var tableKey = $"{host.Name.Parts[0]}.{host.Name.Parts[1]}";
                if (!tablesByKey.TryGetValue(tableKey, out var table))
                {
                    continue;
                }

                var columnsByName = table.Columns.ToDictionary(c => c.Name, StringComparer.OrdinalIgnoreCase);

                var primaryKey = new SimplePrimaryKey
                {
                    Name = pkObj.Name.HasName ? pkObj.Name.Parts[1] : null,
                };

                foreach (var colRef in pkObj.GetReferenced(PrimaryKeyConstraint.Columns, DacQueryScopes.UserDefined))
                {
                    if (columnsByName.TryGetValue(colRef.Name.Parts[2], out var dbCol))
                    {
                        primaryKey.Columns.Add(dbCol);
                    }
                }

                table.PrimaryKey = primaryKey;
            }

            foreach (var fkObj in model.GetObjects(DacQueryScopes.UserDefined, ForeignKeyConstraint.TypeClass))
            {
                var hostRefs = fkObj.GetReferenced(ForeignKeyConstraint.Host, DacQueryScopes.UserDefined).ToList();
                if (hostRefs.Count == 0)
                {
                    continue;
                }

                var host = hostRefs[0];
                var tableKey = $"{host.Name.Parts[0]}.{host.Name.Parts[1]}";
                if (!tablesByKey.TryGetValue(tableKey, out var table))
                {
                    continue;
                }

                var foreignTableRefs = fkObj.GetReferenced(ForeignKeyConstraint.ForeignTable, DacQueryScopes.UserDefined).ToList();
                if (foreignTableRefs.Count == 0)
                {
                    continue;
                }

                var foreignTableRef = foreignTableRefs[0];
                var principalKey = $"{foreignTableRef.Name.Parts[0]}.{foreignTableRef.Name.Parts[1]}";
                if (!tablesByKey.TryGetValue(principalKey, out var principalTable))
                {
                    continue;
                }

                var tableColumnsByName = table.Columns.ToDictionary(c => c.Name, StringComparer.OrdinalIgnoreCase);
                var principalColumnsByName = principalTable.Columns.ToDictionary(c => c.Name, StringComparer.OrdinalIgnoreCase);

                var foreignKey = new SimpleForeignKey
                {
                    Name = fkObj.Name.HasName ? fkObj.Name.Parts[1] : null,
                    PrincipalTable = principalTable,
                };

                foreach (var colRef in fkObj.GetReferenced(ForeignKeyConstraint.Columns, DacQueryScopes.UserDefined))
                {
                    if (tableColumnsByName.TryGetValue(colRef.Name.Parts[2], out var dbCol))
                    {
                        foreignKey.Columns.Add(dbCol);
                    }
                }

                foreach (var colRef in fkObj.GetReferenced(ForeignKeyConstraint.ForeignColumns, DacQueryScopes.UserDefined))
                {
                    if (principalColumnsByName.TryGetValue(colRef.Name.Parts[2], out var dbCol))
                    {
                        foreignKey.PrincipalColumns.Add(dbCol);
                    }
                }

                if (foreignKey.PrincipalColumns.Count > 0)
                {
                    table.ForeignKeys.Add(foreignKey);
                }
            }

            return tables;
        }

        private static Dictionary<string, string> GetTableComments(TSqlModel model)
        {
            var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

            foreach (var ep in model.GetObjects(DacQueryScopes.UserDefined, ExtendedProperty.TypeClass))
            {
                var parts = ep.Name.Parts;
                if (parts.Count == 4
                    && string.Equals(parts[0], "SqlTableBase", StringComparison.OrdinalIgnoreCase)
                    && string.Equals(parts[3], "MS_Description", StringComparison.OrdinalIgnoreCase))
                {
                    var value = ep.GetProperty<string>(ExtendedProperty.Value);
                    if (!string.IsNullOrEmpty(value))
                    {
                        result[$"{parts[1]}.{parts[2]}"] = FixExtendedPropertyValue(value) ?? value;
                    }
                }
            }

            return result;
        }

        private static Dictionary<string, string> GetColumnComments(TSqlModel model)
        {
            var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

            foreach (var ep in model.GetObjects(DacQueryScopes.UserDefined, ExtendedProperty.TypeClass))
            {
                var parts = ep.Name.Parts;
                if (parts.Count == 5
                    && string.Equals(parts[0], "SqlColumn", StringComparison.OrdinalIgnoreCase)
                    && string.Equals(parts[4], "MS_Description", StringComparison.OrdinalIgnoreCase))
                {
                    var value = ep.GetProperty<string>(ExtendedProperty.Value);
                    if (!string.IsNullOrEmpty(value))
                    {
                        result[$"{parts[1]}.{parts[2]}.{parts[3]}"] = FixExtendedPropertyValue(value) ?? value;
                    }
                }
            }

            return result;
        }

        private static Dictionary<string, (string StoreType, string TypeName)> GetTypeAliases(TSqlModel model)
        {
            var result = new Dictionary<string, (string, string)>(StringComparer.OrdinalIgnoreCase);

            foreach (var udt in model.GetObjects(DacQueryScopes.UserDefined, DataType.TypeClass))
            {
                var isMax = udt.GetProperty<bool>(DataType.UddtIsMax);
                var length = isMax ? -1 : udt.GetProperty<int>(DataType.UddtLength);
                var precision = udt.GetProperty<int>(DataType.UddtPrecision);
                var scale = udt.GetProperty<int>(DataType.UddtScale);

                var baseTypes = udt.GetReferenced(DataType.Type).ToList();
                if (baseTypes.Count == 0)
                {
                    continue;
                }

                var baseTypeName = baseTypes[0].Name.Parts[0];
                var storeType = GetStoreType(baseTypeName, length, precision, scale);
                result[$"{udt.Name.Parts[0]}.{udt.Name.Parts[1]}"] = (storeType, baseTypeName);
            }

            return result;
        }

        private static string GetColumnStoreType(TSqlObject colObj, Dictionary<string, (string StoreType, string TypeName)> typeAliases)
        {
            var dataTypeRefs = colObj.GetReferenced(Column.DataType).ToList();
            if (dataTypeRefs.Count == 0)
            {
                return "unknown";
            }

            var dataTypeRef = dataTypeRefs[0];
            var parts = dataTypeRef.Name.Parts;

            if (parts.Count > 1
                && typeAliases.TryGetValue(
                    string.Create(CultureInfo.InvariantCulture, $"{parts[0]}.{parts[1]}"),
                    out var aliasInfo))
            {
                return aliasInfo.StoreType;
            }

            var dataTypeName = parts[0];
            var isMax = colObj.GetProperty<bool>(Column.IsMax);
            var length = isMax ? -1 : colObj.GetProperty<int>(Column.Length);
            var precision = colObj.GetProperty<int>(Column.Precision);
            var scale = colObj.GetProperty<int>(Column.Scale);

            return GetStoreType(dataTypeName, length, precision, scale);
        }

        private static string GetStoreType(string dataTypeName, int maxLength, int precision, int scale)
        {
            if (string.Equals(dataTypeName, "timestamp", StringComparison.OrdinalIgnoreCase))
            {
                return "rowversion";
            }

            if (string.Equals(dataTypeName, "sysname", StringComparison.OrdinalIgnoreCase))
            {
                return "nvarchar(128)";
            }

            if (string.Equals(dataTypeName, "decimal", StringComparison.OrdinalIgnoreCase)
                || string.Equals(dataTypeName, "numeric", StringComparison.OrdinalIgnoreCase))
            {
                return string.Format(CultureInfo.InvariantCulture, "{0}({1}, {2})", dataTypeName, precision, scale);
            }

            if (DateTimePrecisionTypes.Contains(dataTypeName) && scale != 7)
            {
                return string.Format(CultureInfo.InvariantCulture, "{0}({1})", dataTypeName, scale);
            }

            if (MaxLengthRequiredTypes.Contains(dataTypeName))
            {
                return maxLength == -1
                    ? string.Format(CultureInfo.InvariantCulture, "{0}(max)", dataTypeName)
                    : string.Format(CultureInfo.InvariantCulture, "{0}({1})", dataTypeName, maxLength);
            }

            return dataTypeName;
        }

        private static string? FixExtendedPropertyValue(string? value)
        {
            if (value == null)
            {
                return null;
            }

            if (value.StartsWith("N'", StringComparison.Ordinal))
            {
                value = value[2..];
            }

            if (value.StartsWith('\''))
            {
                value = value[1..];
            }

            if (value.EndsWith('\''))
            {
                value = value[..^1];
            }

            return value;
        }
    }
}
