using System.Xml.Linq;
using Microsoft.Data.SqlClient;
using MSBuild.Sdk.SqlProj.DacpacTool;

namespace MSBuild.Sdk.SqlProj.Publishing.IntegrationTests;

[TestClass]
[TestCategory("Publishing")]
public sealed class ReferencedScriptContextTests
{
    private static PublishingFixture _fixture = null!;
    private static string _auditDatabase = "";
    private static string _defaultDatabase = "";

    public TestContext TestContext { get; set; } = null!;

    [ClassInitialize]
    public static async Task InitializeAsync(TestContext context)
    {
        _fixture = new PublishingFixture(context);
        try
        {
            await _fixture.InitializeAsync();
            _auditDatabase = $"ScriptAudit_{Guid.NewGuid():N}";
            _defaultDatabase = $"LoginDefault_{Guid.NewGuid():N}";
            await ExecuteAsync($"CREATE DATABASE [{_auditDatabase}]; CREATE DATABASE [{_defaultDatabase}];", context.CancellationToken);
            await ExecuteAsync($"""
                CREATE TABLE [{_auditDatabase}].dbo.ScriptContext
                (
                    Sequence int IDENTITY PRIMARY KEY,
                    CaseId nvarchar(32) NOT NULL,
                    Phase nvarchar(20) NOT NULL,
                    ActualDatabase sysname NOT NULL,
                    TargetVariable sysname NOT NULL,
                    TargetExists bit NOT NULL
                );
                """, context.CancellationToken);
        }
        catch
        {
            await _fixture.DisposeAsync();
            throw;
        }
    }

    [ClassCleanup]
    public static async Task CleanupAsync() => await _fixture.DisposeAsync();

    [TestMethod]
    [DataRow(false, false, true, "none")]
    [DataRow(true, false, true, "none")]
    [DataRow(false, true, true, "none")]
    [DataRow(true, true, true, "none")]
    [DataRow(false, true, false, "none")]
    [DataRow(true, true, false, "none")]
    [DataRow(true, true, true, "use")]
    [DataRow(false, true, true, "guarded")]
    [DataRow(true, true, true, "guarded")]
    public async Task PublishDatabase_RecordsReferencedScriptContext(bool targetExists, bool customDefault, bool runScripts, string contextSwitch)
    {
        var caseId = Guid.NewGuid().ToString("N");
        var target = $"Target_{caseId}";
        var login = $"Login_{caseId}";
        var initialDatabase = customDefault ? _defaultDatabase : "master";
        var project = CreateProjects(caseId, contextSwitch);
        if (targetExists)
        {
            await ExecuteAsync($"CREATE DATABASE [{target}];", TestContext.CancellationToken);
        }
        // Names and password are generated by the fixture, not external input.
        await ExecuteAsync($"""
            CREATE LOGIN [{login}] WITH PASSWORD = '{_fixture.Password}', CHECK_POLICY = OFF, DEFAULT_DATABASE = [{initialDatabase}];
            ALTER SERVER ROLE sysadmin ADD MEMBER [{login}];
            """, TestContext.CancellationToken);

        await _fixture.RunAsync("dotnet", "publish", project, "-c", "Release", "/t:PublishDatabase", _fixture.ToolProperty,
            $"/p:TargetServerName={_fixture.SqlServer.Hostname}", $"/p:TargetPort={_fixture.SqlServer.GetMappedPublicPort(1433)}",
            $"/p:TargetDatabaseName={target}", $"/p:TargetUser={login}", $"/p:TargetPassword={_fixture.Password}",
            $"/p:RunScriptsFromReferences={runScripts}");

        await _fixture.AssertTableAsync(target);
        var observations = await ReadObservationsAsync(caseId);
        if (!runScripts)
        {
            Assert.IsEmpty(observations);
            return;
        }

        var switched = contextSwitch == "use" || (contextSwitch == "guarded" && targetExists);
        Assert.HasCount(switched ? 3 : 2, observations);
        Assert.AreEqual(new Observation("pre", initialDatabase, target, targetExists), observations[0]);
        if (switched)
        {
            Assert.AreEqual(new Observation("pre-target", target, target, true), observations[1]);
        }
        Assert.AreEqual(new Observation("post", target, target, true), observations[^1]);
    }

    [TestMethod]
    public async Task DeploymentHelper_ExplicitInitialCatalogDiffersFromTarget()
    {
        var caseId = Guid.NewGuid().ToString("N");
        var target = $"Target_{caseId}";
        var project = CreateProjects(caseId, "none");
        await _fixture.RunAsync("dotnet", "build", project, "-c", "Release", _fixture.ToolProperty);
        var package = new FileInfo(Path.Combine(Path.GetDirectoryName(project)!, "bin", "Release", "net10.0", "Main.dacpac"));
        var deployer = new PackageDeployer(new ActualConsole());
        deployer.ConnectionStringBuilder.ConnectionString = _fixture.SqlServer.GetConnectionString();
        deployer.ConnectionStringBuilder.InitialCatalog = _defaultDatabase;
        deployer.SetDeployProperty("IncludeCompositeObjects=True");

        // This is a helper-level case: PublishDatabase exposes no connection-string/Initial Catalog option.
        deployer.RunPreDeploymentScriptFromReferences(package, target);
        Assert.IsTrue(deployer.Deploy(package, target));
        deployer.RunPostDeploymentScriptFromReferences(package, target);

        await _fixture.AssertTableAsync(target);
        var observations = await ReadObservationsAsync(caseId);
        Assert.HasCount(2, observations);
        Assert.AreEqual(new Observation("pre", _defaultDatabase, target, false), observations[0]);
        Assert.AreEqual(new Observation("post", target, target, true), observations[1]);
    }

    private static string CreateProjects(string caseId, string contextSwitch)
    {
        var caseDirectory = Path.Combine(_fixture.WorkspaceDirectory, caseId);
        var reference = Path.Combine(caseDirectory, "Reference");
        var main = Path.Combine(caseDirectory, "Main");
        Directory.CreateDirectory(Path.Combine(reference, "Pre-Deployment"));
        Directory.CreateDirectory(Path.Combine(reference, "Post-Deployment"));
        Directory.CreateDirectory(main);
        var template = XDocument.Load(_fixture.ProjectPath);
        var properties = new XElement("PropertyGroup",
            new XElement("TargetFramework", "net10.0"),
            new XElement("SqlServerVersion", "Sql160"));
        var imports = template.Root!.Elements("Import").ToArray();
        var referenceProject = new XDocument(new XElement("Project", new XElement(imports[0]), new XElement(properties),
            new XElement("ItemGroup",
                new XElement("PreDeploy", new XAttribute("Include", "Pre-Deployment/Pre.sql")),
                new XElement("PostDeploy", new XAttribute("Include", "Post-Deployment/Post.sql"))),
            new XElement(imports[1])));
        referenceProject.Save(Path.Combine(reference, "Reference.csproj"));
        File.WriteAllText(Path.Combine(reference, "ReferenceTable.sql"), "CREATE TABLE dbo.ReferenceTable (Id int NOT NULL);\n");
        var pre = RecordContext(caseId, "pre");
        if (contextSwitch == "use")
        {
            pre += "\nUSE [$(DatabaseName)];\nGO\n" + RecordContext(caseId, "pre-target");
        }
        else if (contextSwitch == "guarded")
        {
            var targetScript = "USE [$(DatabaseName)]; " + RecordContext(caseId, "pre-target");
            pre += $"\nIF DB_ID(N'$(DatabaseName)') IS NOT NULL\n    EXEC(N'{targetScript.Replace("'", "''", StringComparison.Ordinal)}');\n";
        }
        File.WriteAllText(Path.Combine(reference, "Pre-Deployment", "Pre.sql"), pre);
        File.WriteAllText(Path.Combine(reference, "Post-Deployment", "Post.sql"), RecordContext(caseId, "post"));
        var mainProject = new XDocument(new XElement("Project", new XElement(imports[0]), new XElement(properties),
            new XElement("ItemGroup", new XElement("ProjectReference", new XAttribute("Include", "../Reference/Reference.csproj"))),
            new XElement(imports[1])));
        var path = Path.Combine(main, "Main.csproj");
        mainProject.Save(path);
        File.Copy(Path.Combine(_fixture.WorkspaceDirectory, "Tables", "MyTable.sql"), Path.Combine(main, "MyTable.sql"));
        return path;
    }

    private static string RecordContext(string caseId, string phase) => $"""
        INSERT [{_auditDatabase}].dbo.ScriptContext (CaseId, Phase, ActualDatabase, TargetVariable, TargetExists)
        VALUES (N'{caseId}', N'{phase}', DB_NAME(), N'$(DatabaseName)', CASE WHEN DB_ID(N'$(DatabaseName)') IS NULL THEN 0 ELSE 1 END);
        """;

    private static async Task ExecuteAsync(string sql, CancellationToken cancellationToken)
    {
        await using var connection = new SqlConnection(_fixture.SqlServer.GetConnectionString());
        await connection.OpenAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    private async Task<List<Observation>> ReadObservationsAsync(string caseId)
    {
        await using var connection = new SqlConnection(_fixture.SqlServer.GetConnectionString());
        await connection.OpenAsync(TestContext.CancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = $"SELECT Phase, ActualDatabase, TargetVariable, TargetExists FROM [{_auditDatabase}].dbo.ScriptContext WHERE CaseId = @caseId ORDER BY Sequence";
        command.Parameters.AddWithValue("@caseId", caseId);
        await using var reader = await command.ExecuteReaderAsync(TestContext.CancellationToken);
        var observations = new List<Observation>();
        while (await reader.ReadAsync(TestContext.CancellationToken))
        {
            var observation = new Observation(reader.GetString(0), reader.GetString(1), reader.GetString(2), reader.GetBoolean(3));
            observations.Add(observation);
            TestContext.WriteLine(observation.ToString());
        }
        return observations;
    }

    private sealed record Observation(string Phase, string ActualDatabase, string TargetVariable, bool TargetExists);
}
