name: Docs

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/docfx.yml"
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Install DocFX
        run: dotnet tool install -g docfx --version 2.78.5

      - name: Build site
        run: docfx docs/docfx.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
